site_name: База знаний по Электронному бюджету
site_url: https://ebudget-community.ru

docs_dir: docs

repo_url: https://gitverse.ru/ebudget-community/docs
repo_name: gitverse/ebudget-community/docs

nav:
  - Главная: index.md
  - О проекте:
    - about/index.md
    - about/issues.md
    - about/contacts.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt 
  language: ru
  features:
    - content.tabs.link
    - content.code.copy
    - navigation.expand
    - navigation.tabs
    - navigation.indexes
    - toc.integrate

markdown_extensions:
  # Обычные
  - admonition
  - attr_list
  - toc:
      permalink: true
  # PyMdownX
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      base_path:
        - docs/
      check_paths: true

      # Указанные в этом списке файлы будут автоматически добавляться ко всем Markdown файлам
      auto_append:
        - assets/links.md
        - assets/images.md

  - pymdownx.tilde

extra_css:
  - assets/extra.css

extra:
  social:
    - name: GitVerse
      icon: fontawesome/brands/git-alt
      link: https://gitverse.ru/ebudget-community/docs
    - name: GitFlic (Зеркало)
      icon: fontawesome/brands/gitlab
      link: https://gitflic.ru/project/ebudget-community/docs
    - name: GitHub (Зеркало)
      icon: fontawesome/brands/github
      link: https://github.com/ebudget-community/docs
    - name: Telegram
      icon: fontawesome/brands/telegram 
      link: https://t.me/ebudget_community

plugins:
  - search
  - minify:
      minify_html: true
  - exclude:
      glob:
        - assets/*.md
  - table-reader

validation:
  links:
    # Все абсолютные ссылки резолвятся относительно docs/ (корня документации)
    absolute_links: relative_to_docs
    anchors: warn
#    unrecognized_links: warn
